### ISSUE TITLE
`ifElse` violates our decalogue

### ISSUE THREAD

**Issue by tomekwi** [1-liners/1-liners#104]
https://github.com/1-liners/1-liners/blob/28b02d0939d6bb4034693e48440f450141453ae9/module/ifElse.js#L27

It doesn’t have a stable number of arguments. I suggest splitting this down into two functions:

```js
export const ifThen (predicate, then) => …
export const ifThenElse (predicate, then, else) => …
```

Then it’ll also be more clear from the name of the function what it does.

**Comment by stoeffel** [comment]
:+1: SGTM

**Comment by hemanth** [comment]
:+1:
