### ISSUE TITLE
String functions

### ISSUE THREAD

**Issue by tomekwi** [1-liners/1-liners#108]
* [x] [charAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charAt)
* [x] [charCodeAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt)
* [x] [codePointAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt)
* ~~[concat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat) (is it needed when we have `plus`?)~~
* [x] [endsWith](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith)
* [x] [includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)
* [x] [indexOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf)
* [x] [lastIndexOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf)
* [x] [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare)
* [x] [match](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match)
* [x] [normalize](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize)
* [x] [repeat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat)
* [x] [replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace)
* [x] [search](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search)
* [x] [slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice)
* [x] [split](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split)
* [x] [startsWith](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith)
* ~~[substr](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr)~~
* ~~[substring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring)~~
* ~~[toLocaleLowerCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase)~~
* ~~[toLocaleUpperCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleUpperCase)~~
* [x] [toLowerCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase)
* ~~[toString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toString) (does it make sense? we have the native `String()`)~~
* [x] [toUpperCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase)
* [x] [trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim)
* ~~[valueOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/valueOf)~~

**Comment by tomekwi** [comment]
Hmm, why would we need to differentiate between toUpperCase and toLocaleUpperCase? Same with lowercase. Let’s decide for one option.

I always use the simple variant – but perhaps the locale version is more generic?

**Comment by stoeffel** [comment]
I would go with the none locale version since it's used more often and drop the locale version.

**Comment by tomekwi** [comment]
:+1:

**Comment by tomekwi** [comment]
I’ve also striked `valueOf` through. I’ve never used it (used `Number`, `String`, `Boolean` etc instead). And [as the MDN says](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/valueOf):

> This method is usually called internally by JavaScript and not explicitly in code.

**Comment by tristaaan** [comment]
Without their optional arguments `substr(startIndex[, length])` and `substring(startIndex[, end])` behave the same way. Should they be split apart like `startsWith` and `startsWithAt`? As in:

`substr(start, str) / substrLen(start, len, str)`

`substring(start, str) / substringTo(start, end, str)`

**Comment by stoeffel** [comment]
Jop, you are right substr should be splitted like startsWith. I would prefer substrTo.

**Comment by tristaaan** [comment]
Updated checklist after merge #142

**Comment by huei90** [comment]
I have complete the lists.
`replace` already exists in project.

https://github.com/1-liners/1-liners/pull/151

**Comment by tomekwi** [comment]
Hmmmhm, https://github.com/1-liners/1-liners/pull/151#issuecomment-154398518 didn’t close this after all. Sometimes I don’t quite get this GitHub thing.

**Comment by stoeffel** [comment]
It only works if you write f.e. "fixes #n" in the commit message. It doesn't work if you write it in a comment.

**Comment by tomekwi** [comment]
Ahh, now it makes sense!
