### ISSUE TITLE
Function functions

### ISSUE THREAD

**Issue by tomekwi** [1-liners/1-liners#112]
* ~~[apply](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply)~~
* [x] [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)
* ~~[call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call)~~
* ~~[toString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString) (does it make sense? we have the native `String()`)~~

**Comment by stoeffel** [comment]
do we really need this functions? just to bind `this`? then lets just add bind. we have curry explode and so on. and call has no stable number of arguments.

**Comment by tomekwi** [comment]
That’s right. I just copied all of them over like a robot :)

However, if we decide to pick https://github.com/1-liners/1-liners/issues/113#issuecomment-111266914 as a selling point, we could mention it in the docs. For example list `apply` in the docs, but link to `bind` and `implode` from there. Or have some sort of tagging functionality and tag `bind` and `implode` with `call` as well.

**Comment by tomekwi** [comment]
> However, if we decide to pick #113 (comment) as a selling point…

We don’t have to though if it’s overkill. It’s just that these functions are extremely easy to test, write, and even generate. And I feel that the need for an alternative to the javaesque `object.method()` cruft is there. Together with JavaScript’s confusing `this` and unbinding/binding. Perhaps such a collection of drop-in alternatives would really be good.

**Comment by stoeffel** [comment]
> We don’t have to though if it’s overkill. @stoeffel?

I still think it's a little overkill. What do you think @hemanth?

**Comment by tomekwi** [comment]
I’ve just left `bind` in the todo list

**Comment by stoeffel** [comment]
:+1:
