### ISSUE TITLE
Remove `npm test` from the prepush hook

### ISSUE THREAD

**Issue by tomekwi** [1-liners/1-liners#122]
After having worked with the prepush hook for some time I find it a bit annoying. When releasing a new version I have to wait for the tests to complete 5 times:

* pushing `master` to my local mirror
* pushing `--tags` to my local mirror
* pushing `master` to github
* pushing `--tags` to github
* `npm publish`

I think it would be enough to run the tests one on `prepublish`. Because that’s what we care about – avoiding a broken release. And as for tests upon every push – that’s what travis is for, isn’t it?

**Comment by stoeffel** [comment]
:+1: yep. Was annoyed by this too.

**Comment by hemanth** [comment]
:+1: 

P.S: Gentelmen do contribute to [npm-scripts](https://github.com/npm-scripts) ;)
