### ISSUE TITLE
microjs

### ISSUE THREAD

**Issue by stoeffel** [1-liners/1-liners#128]
What do you think guys should we add 1-liners to [madrobby/microjs.com](https://github.com/madrobby/microjs.com) ?

**Comment by hemanth** [comment]
Yes :+1:

**Comment by tomekwi** [comment]
:+1:

**Comment by stoeffel** [comment]
We have to check if the lib follows all the rules.
- [ ] Must not have dependencies (It's ok to target a specific platform, like Node.js or WebKit)
- [ ] Must do something useful, and must not be just a demo
- [x] Must be MIT/BSD-license or similar permissive license
- [x] Templating engines and loaders will only be added if they're outstanding and exceptional
- [ ] Must be < 5k when minified and gzipped (see below)
- [ ] Source file must be available for download and not change across releases (e.g. awesomesauce-1.1.0.js)
- [ ] Prefer hand-coded/hand-optimized JavaScript over generated/cross-compiled code

- [ ] To check the minified and compressed size of your library from the command line, either use ./build.js -v (see below) or run:
$ uglifyjs yourlib.js | gzip -9f | wc -c

**Comment by stoeffel** [comment]
We will have to create a npm task to build the lib into one file.

**Comment by hemanth** [comment]
> Must be < 5k when minified and gzipped

**Comment by stoeffel** [comment]
@hemanth ?

**Comment by tomekwi** [comment]
> We will have to create a npm task to build the lib into one file.

…

> Source file must be available for download and not change across releases (e.g. awesomesauce-1.1.0.js)

https://wzrd.in/standalone/1-liners@0.3.5 could do it. But somehow browserify seems to choke on *1-liners*.

**Comment by stoeffel** [comment]
> choke on 1-liners.

probably because it's not built (still es6)

build-task should first compile and then create a standalone from it using browserify.

**Comment by tomekwi** [comment]
> probably because it's not built (still es6)

Nope – wzrd.in takes http://registry.npmjs.org/1-liners/-/1-liners-0.3.5.tgz and that has the ES5 version built in.

**Comment by stoeffel** [comment]
It works with bundle see http://jsbin.com/fotalokope/edit?html,js,output

related issue: https://github.com/jfhbrook/browserify-cdn/issues/74

**Comment by tomekwi** [comment]
Good catch!
