### ISSUE TITLE
compose() arity

### ISSUE THREAD

**Issue by guumaster** [1-liners/1-liners#131]
The `compose()` function in `1-liners` only accepts two functions as parameters. Other implementations accepts any number of arguments. Ex: [fj-compose](https://github.com/fp-js/fj-compose). 

Is it possible to accept more arguments and still comply to the `1-liners` decalogue?

**Comment by stoeffel** [comment]
We discussed this [here](https://github.com/1-liners/1-liners/pull/27#issuecomment-97683671). IMO this is okay as is. The only possibility I see is to add a `composeAll(arrayOfFunctions)` and `pipeAll(arrayOfFunctions)`. Checkout [stoeffel/compose-function](https://github.com/stoeffel/compose-function) as an alternative.

**Comment by guumaster** [comment]
:+1:  composeAll and pipeAll.

**Comment by stoeffel** [comment]
@1-liners/owners what are your opinions? It's good for me.
