### ISSUE TITLE
es6 and curried folders

### ISSUE THREAD

**Issue by guumaster** [1-liners/1-liners#134]
If we rename `module` folder to `es6`, then all developers can include es6 version directly into their code. Same for the curried version of every function. Imports could be like this: 

```javascript
// es6, not transpiled
import { compose } from '1-liners/es6';

// es6, transpiled
import { compose } from '1-liners';

// es6, curried, transpiled
import { compose } from '1-liners/curried'; 

// es6, curried, not transpiled
import { compose } from '1-liners/es6/curried';

// all functions es6
import { * from L1 } from '1-liners/es6';

// all functions es6 curried
import { * from L1 } from '1-liners/es6/curried';

// all es5 not curried
var L1 = require('1-liners');

// all es5, curried
var L1 = require('1-liners/curried');

// es5, not curried
var compose = require('1-liners/compose');

// es5, curried
var compose = require('1-liners/curried/compose');
``` 

Adding a step on the build script to have  `curried` folders (es6 and transpiled) should be easy. What do you think?

**Comment by stoeffel** [comment]
Hmmm... I actually would prefer to have the curried 1-liners in a separate repo https://github.com/1-liners/1-liners-curried. Because users who want to use the curried version don't need the uncurried version.

**Comment by tomekwi** [comment]
@stoeffel :+1:

**Comment by tomekwi** [comment]
@guumaster we discussed the name of the `module` folder once and concluded that it’s a good, explicit name. Modules first came with ES 2015, but they will work in ES 2016+ – there’s no need to lock the name to a version of ES.

As for the `/curried` proposal – I once was a great fan of such imports. But a discussion with @mattdesl made me change my mind: <https://github.com/mattdesl/module-best-practices/pull/2>. Definitely worth skimming through, the first three or four statements.

**Comment by guumaster** [comment]
Cool, convinced of not doing any of this :smile:. I saw there is a `1-liners-curried` in place already.

Also, added [module-best-practices repo](https://github.com/mattdesl/module-best-practices) to my reading list. Thanks.
