### ISSUE TITLE
flatMap/chain

### ISSUE THREAD

**Issue by davidchase** [1-liners/1-liners#138]
Any interest in adding some like flatMap/chain?

```js
// in terms of reduce
const flatMap = (fn, xs) => xs.reduce((acc, x) => acc.concat(fn(x)), []);
// in terms of map
const flatMap = (fn, xs) => [].concat.apply([], xs.map(fn));
```

didnt see it on this list https://github.com/1-liners/1-liners/issues/107

**Comment by stoeffel** [comment]
Sure, would be cool! Are you interested in making a PR?

**Comment by davidchase** [comment]
sounds good, do you have a name preference? and which would you prefer in terms of `reduce` or `map` ?

**Comment by stoeffel** [comment]
`flatMap` sgtm and I would prefer `map`

Any other opinions @1-liners/owners?

**Comment by tomekwi** [comment]
:+1:

**Comment by davidchase** [comment]
all set let me know #139
