### ISSUE TITLE
Add list/string drop and rename drop to omit

### ISSUE THREAD

**Issue by davidchase** [1-liners/1-liners#140]
So small proposal let me know what you guys think...

For a better user experience for people coming from lodash, ramda, etc or even functional languages like haskell... imho the current implementation of [drop](https://github.com/1-liners/1-liners/tree/master/documentation#drop) would be renamed to `omit`.

And we could implement `drop` like so `const drop = (n, xs) => xs.slice(Math.max(n, 0), Infinity);`
then use like so
```js
drop(3, [1,2,3,4,5]) //=> [4,5]

// can be used on strings as well
drop(6, "hello world") // world
```

thoughts @1-liners/owners ?

**Comment by stoeffel** [comment]
Good idea. :+1:

**Comment by tomekwi** [comment]
:+1: :+1:
