### ISSUE TITLE
defaultTo util

### ISSUE THREAD

**Issue by davidchase** [1-liners/1-liners#145]
Hey guys any interest in a defaultValue utility with a bit of a twist :wink: 

```js
const defaultTo =  (x) => (...y) => y.filter((x) => x)[0] || x;

defaultToSomething = defaultTo('some default value');
defaultToSomething(null) //=> 'some default value'
defaultToSomething(NaN, null, undefined, 'hey captain'); //=> 'hey captain' 

// similar to short circuit
NaN || null || undefined || 'hey captain'
```

**Comment by tomekwi** [comment]
Looks fun – but I can’t think of a real-world use for this. When writing a function without ES 2015 defaults, I think I’d prefer a simple `defaultToSomething(null, 'hey captain');  //» 'hey captain'`.

**Comment by stoeffel** [comment]
> I think I’d prefer a simple defaultTo(null, 'hey captain'); //» 'hey captain'.

Same here. It should be as simple as possible to understand what a 1-liner is doing.

But `defaultTo` is actually the same as [`or`](https://github.com/1-liners/1-liners/tree/master/documentation#or)

```js
or(null, 'hey captain'); //» 'hey captain'
```

**Comment by stoeffel** [comment]
But how about:

```js
shortCircuit([(NaN, null, undefined, 'hey captain']); //=> 'hey captain'
// same as NaN || null || undefined || 'hey captain'
```

**Comment by davidchase** [comment]
@tomekwi we actual use this ƒ at work with a different name without es6.

@stoeffel your `shortCircuit` method sounds like it should be called `either` no?

i didnt think it would hold much ground, so its cool to me if you guys want to close it

**Comment by stoeffel** [comment]
> your shortCircuit method sounds like it should be called either no?

yop

**Comment by davidchase** [comment]
which could as simple as
`const either = xs => xs.filter((x) => x)[0];`
