### ISSUE TITLE
Any interest in range?

### ISSUE THREAD

**Issue by davidchase** [1-liners/1-liners#148]
```js 
const range = (from, to) => Array.from(Array(to - from).keys()).map((key) => key + from);
```

```js
range(1, 10) //=> [1,2,3,4,5,6,7,8,9]
```
i can see the possible issue with `Array.prototype.keys` might not be supported so how about

```js
const range = (from, to) => Array(to - from).fill().map((key, index) => index + from);
```

[Array.prototype.fill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill) can be [polyfilled](https://github.com/ahutchings/Array.prototype.fill) :wink:

**Comment by stoeffel** [comment]
How about a solution without any polyfill?
```js
const range = (from, to) => from === to? [from]: [from, ...range(from + 1, to)]
```
I think babel should optimise the recursion.

**Comment by davidchase** [comment]
that solution http://goo.gl/aIAaPN returns inclusive result such as `range(1, 5) //=> [1,2,3,4,5]`
where i think the expected result should be `[1,2,3,4]`

also if a user inputs `range(10, 10)` it should be `[]` rather than `[10]`

what you think of 
```js
const range = (from, to) => from === to? []: [from, ...range(from + 1, to)]
```
so empty `[]` if `from === to`

**Comment by stoeffel** [comment]
yop, agreed :-)

**Comment by stoeffel** [comment]
btw. http://davidchase.github.io/ramtuary/ is awesome :+1:

**Comment by davidchase** [comment]
> btw. http://davidchase.github.io/ramtuary/ is awesome :+1:

thanks :smile: 

do you want me to start a PR with your concept or will you add it?

**Comment by stoeffel** [comment]
You can do it if you like. I want have time until sunday.

**Comment by tristaaan** [comment]
Would something like `rangeWithStep` work along with this? 
```js
const rangeWithStep = (from, to, stepFunc) => from >= to? []: [from, ...rangeWithStep(stepFunc(from), to, stepFunc)];
const addThree = (a) => a + 3;
rangeWithStep(0,10, addThree); // => [0,3,6,9]
```

Instead of taking a function it could just take a constant too, so `rangeWithStep(0,10,3)`. Might be more readable and straightforward.

**Comment by stoeffel** [comment]
Yop, `rangeWithStep` would be nice. I like the one with the step function better. But the one with the constant would probably fit better.

**Comment by davidchase** [comment]
> Would something like rangeWithStep work along with this?

that is pretty nice, with the step ƒ

 i took your @stoeffel recursion idea a little further and created an unfold PR #149 that will allow the end-user to make their own range, etc let me know what you guys think

**Comment by stoeffel** [comment]
@davidchase awesome. Will have a look tomorrow.
