### ISSUE TITLE
More parameter

### ISSUE THREAD

**Issue by huei90** [1-liners/1-liners#152]
When I'm writing the script, i have a question about the parameter.

In String.indexOf case,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf

we can have two parameters with one optional.

In 1-liners script
https://github.com/1-liners/1-liners/blob/master/module/indexOf.js

We can have only one parameter.

People cannot use the second parameter

**Comment by tomekwi** [comment]
Yeah, we have a rule that [every function has a fixed arity](https://github.com/1-liners/1-liners/blob/45a3f4a3142292bcfd64a76de365f35e311d77f7/README.md#our-decalogue). If you really need a two-param variant of a function, just write a new function.

There are good reasons for this! Try this: `[1, 2, 3].map(parseInt)` and try to figure out why!

**Comment by huei90** [comment]
By given your example, we can rewrite them to
`map(parseInt, [1, 2, 3])`

I'm still not figure out why, but `map(function something(v) {return v;}, [1, 2, 3])` make more sense than `map([1, 2, 3], function something(v){ return v;})` (gut feeling)

**Comment by huei90** [comment]
hmm.. This must be a frequently asked question in this project.

**Comment by tomekwi** [comment]
The “data as last arg” convention comes from pure functional languages and makes lots of sense when partial application and currying are at stake. Even if it looks foreign to most of the JS community.

There’s some more reasoning at [ramda](http://ramdajs.com/0.18.0/index.html) which is a similar library but all-inclusive – with automatic currying among other things.

**Comment by huei90** [comment]
Good point. Let's thinking in functional.

Do you mind giving me some examples why currying is important to functional language?

**Comment by stoeffel** [comment]
Check out stoeffel/awesome-fp-js for awesome resources about fp in js :smiley:

**Comment by huei90** [comment]
Ok thanks @stoeffel

**Comment by stoeffel** [comment]
I can recommend  https://medium.com/@collardeau/intro-to-functional-programming-concepts-in-javascript-b0650773139cc as a starting point.

**Comment by huei90** [comment]
404 page?
