### ISSUE TITLE
Remove composeAll and make compose variadic and recursive 

### ISSUE THREAD

**Issue by stevensacks** [1-liners/1-liners#158]
Currently, you have two functions, compose and composeAll. The former is limited to two functions and the latter requires you to wrap your functions in an array. This creates unnecessary complexity.

The solution is to have one compose function that is variadic (accepts as many functions as you pass), and which uses recursion to eliminate the need for loops, map, or reduce.

Voila!

```
const compose = (fn, ...rest) => rest.length === 0 ? fn : (...args) => fn(compose(...rest)(...args));
```

**Comment by stoeffel** [comment]
hey steven
This would be against 
> Each function shall have a fixed number of arguments
– it’s dead easy to bind, curry and uncurry, apply partially, implode and explode.

(see readme).


if you need a variadict compose function use https://github.com/stoeffel/compose-function

**Comment by stoeffel** [comment]
btw. you can get rid of the recursion with reduce. see https://github.com/stoeffel/compose-function/blob/master/module/index.js

**Comment by stevensacks** [comment]
That's a nice rule in theory, but in practice, I can't think of a scenario where I would want to curry a fixed-argument compose().

**Comment by stoeffel** [comment]
Compose (with fixed arity is actually quiet useful). To wrap the output of a function.
f.e.
```js
const compose2 = curry(compose)
const makeSafe = compose2(toMaybe)
const safeHead = makeSafe(head)
```
and you can create composeAll from it as simple as the following:
````js
const composeAll = (...fns) => fns.reduce(compose)
```
