### ISSUE TITLE
When should I use always

### ISSUE THREAD

**Issue by srinivasdamam** [1-liners/1-liners#163]
```
1. const twentyFour = 24;
2. const twentyFour = always(24)
```
1 and 2 does the same job. I'm curious to know if any advantages of using `always` in this context.  And I have to call `twentyFour()` every time i need it.

**Comment by guumaster** [comment]
Well, 1 and 2 are actually different. `always(24)` returns a function that always return 24. So with `twentyFour` from the second line, you can compose new functions.

Silly example, but say that you need to fill an array with 24. You can do it this way: 

```js
const twentyFour = always(24)

const myList = range(1, 10) // => [1,2,3..,9, 10]

const myTwentyFourList = map(twentyFour, myList) // => [24, 24, 24,.... 24] ten times
```

That's the difference.

**Comment by srinivasdamam** [comment]
Thanks @guumaster . Made sense. Shall I close this as it is not an issue?
