### ISSUE TITLE
Publish new version for added methods since 0.4.1

### ISSUE THREAD

**Issue by Siilwyn** [1-liners/1-liners#200]
:wave: hi there it looks like functions like `range` are not in the last published version on npm but are in the source for some time.

Also while I understand the hesitation to publish 1.0.0 I would love if you'd consider doing this to follow semver:
> Version numbers should be used to avoid dependency hell... There's no reason for keeping the version number low, expect for marketing or maybe emotional attachment to versions. There's this concept in our mind that the version number has something to say about the project or the process or the stability and all of this is wrong... People believe something incredible existing is happening when a major/breaking version is released... Leave your emotions out of this.

(I also made an issue about 1.0 at ramda, take a look at some of the reactions for some more info: https://github.com/ramda/ramda/issues/2337)

**Comment by Siilwyn** [comment]
Hi @hemanth, thoughts?

**Comment by Siilwyn** [comment]
@architectcodes or @stoeffel perhaps?

**Comment by unlight** [comment]
/cc Maintainers
@hemanth
@stoeffel 
@tomekwi
@davidchase
@tristaaan

**Comment by hemanth** [comment]
Okies, as of now published `1-liners@0.4.2` we can see what rest of them say and decide if we can bump to a major version.
