### ISSUE TITLE
Boast about how great this is :)

### ISSUE THREAD

**Issue by tomekwi** [1-liners/1-liners#34]
Mention that:
- [ ] all functions are pure
- [ ] all functions have a stable number of arguments
- [ ] all functions are in one line
- [ ] we have functional versions of many native object methods
- [ ] and functional versions of most operators

How about:
- [ ] showing the source of every function in the readme

**Comment by tomekwi** [comment]
> all functions have a stable number of arguments

Hmm, I now see that it’s not true (`inc` and `dec` for example). @stoeffel I suggest no default values and no overloading. This way it’s easier to curry functions, flip their arguments, explode, implode etc. And it’s easier to wrap your head around it.

You could always do:
```js
const inc = curry(plus)(1);
```

What do you think?

**Comment by tomekwi** [comment]
> I suggest a stable number of arguments, no default values and no overloading.

Oh, and it’s easier to map things as well. See this [recent diff](https://github.com/stoeffel/1-liners/commit/3b5a900c44ef37753a3d01998a13df26e9f32927).

**Comment by stoeffel** [comment]
Sounds great!
Yes, let's change inc dec.

**Comment by hemanth** [comment]
+1 for a link to the source in the readme.

**Comment by tomekwi** [comment]
Or even:

***

### *and*(*a*, *b*)

Same as `a && b`.

```js
var and = require('1-liners/and');

and(true, true); // => true
and(false, true); // => false
```

<sup>Source: <code>(x, y) => x && y;</code></sup>

***

**Comment by stoeffel** [comment]
> Source: (x, y) => x && y;

:+1:

**Comment by stoeffel** [comment]
How about we move documentation to the source files and generate the docs from it? With @tomekwi example as template? We also would have to change the oneliner test to only check for none comment lines.

Example:
```js
/**
 * @module and
 * 
 * Same as `a && b`.
 *
 * @example
 *   var and = require('1-liners/and');
 * 
 *   and(true, true); // => true
 *   and(false, true); // => false
 */
export default (x, y) => x && y;
```

**Comment by hemanth** [comment]
I would vote for something like what lodash's document.

**Comment by stoeffel** [comment]
> I would vote for something like what lodash's document.

What do you mean by that?

**Comment by hemanth** [comment]
![screen shot 2015-05-03 at 9 02 36 pm](https://cloud.githubusercontent.com/assets/18315/7445591/d4dacbc0-f1d7-11e4-9979-7dfc3ba40fec.png)

The `# S N` in the image.

**Comment by tomekwi** [comment]
@hemanth lodash is a monstrous base of code (over 12000 LOC, the file they link to). The “Ⓝ” link itself is there because they have custom builds for single functions released as separate modules!

In our case showing the source inline doesn’t cost much more space than providing just the link. And the minimalism is something to be proud of!

**Comment by tomekwi** [comment]
> How about we move documentation to the source files and generate the docs from it?

Great idea! Then IDEs like WebStorm or Brackets can show the doc while coding :)

**Comment by stoeffel** [comment]
lets close this in favour of #62
