### ISSUE TITLE
isType

### ISSUE THREAD

**Issue by stoeffel** [1-liners/1-liners#48]
Add functions to check if argument is of a type

- [x] isString
- [x] isObject
- [x] isPlainObject
- [x] isBoolean
- [x] isNumber
- [x] isFunction
- [x] isTypeOf === typeof arg === 'function'
- [x] isTrue
- [x] isFalse
- [x] isNull
- [x] isUndefined

**Comment by stoeffel** [comment]
Do we really need `isPlainObject`? What would the simplest implementation look like?

**Comment by tomekwi** [comment]
If we assume an ES6 env, we can do

```js
(value) => [Object.prototype, null].includes(value.__proto__);
```

(not tested)

**Comment by tomekwi** [comment]
And without a polyfill for array.includes:

```js
(value) => (value.__proto__ === Object.prototype || value.__proto__ === null);
```

**Comment by stoeffel** [comment]
> (value) => (value.__proto__ === Object.prototype || value.__proto__ === null);

nice!
