### ISSUE TITLE
lower and greater than

### ISSUE THREAD

**Issue by stoeffel** [1-liners/1-liners#52]
- [ ] lt
- [ ] gt
- [ ] le
- [ ] ge

**Comment by stoeffel** [comment]
Should we name this functions `lt` or `lowerThan`? I tend to `lowerThan`

**Comment by tomekwi** [comment]
:+1: for `lowerThan`

**Comment by tomekwi** [comment]
* `lowerThan`
* `lessThan`
* `isLessThan`

**Comment by stoeffel** [comment]
:+1: for lessThan
