### ISSUE TITLE
How to handle flexible-length functions?

### ISSUE THREAD

**Issue by tomekwi** [1-liners/1-liners#94]
In JS:

[`arr.reduce(callback[, initialValue])`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/array/reduce)

In *1-liners*:

> ### reduce
> 
> Same as `[1, 2, 3].reduce(sum)`.
> 
> ```js
> var reduce = require('1-liners/reduce');
> 
> reduce(sum, [1, 2, 3]); // => 6
> ```
> 
> <div align="right"><sup>
>   <a href="../tests/reduce.js">Spec</a>
>   •
>   <a href="../module/reduce.js">Source</a>: <code> (reduce, arr) =&gt; arr.reduce(reduce);</code>
> </sup></div>

We don’t want to overload the function, because it will make auto-currying impossible. How about this then:

```js
const reduce = require('1-liners/reduce/2');  // or just '1-liners/reduce'

reduce(callback, array);
```

```js
const reduce = require('1-liners/reduce/3');

reduce(callback, array, initialValue);
```

**Comment by tomekwi** [comment]
> https://github.com/studio-b12/doxie-core/commit/bb4aff2f07b29a67f7b05654f58274a71aba8e19#commitcomment-11520905

Ahh, I saw it but got confused. I thought `array.reduceFrom` was a native method I didn’t know of!

We’d need to make the docs more explicit then.

BTW, how about:
* Linking to MDN (like “same as [`array.reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/array/reduce)”)
* using the same variable names in the source as they do on MDN?

**Comment by stoeffel** [comment]
> We’d need to make the docs more explicit then.

How about we link to reduceFrom from reduce?


> Linking to MDN (like “same as array.reduce”)
using the same variable names in the source as they do on MDN?

:+1: to all of that.

**Comment by tomekwi** [comment]
Closing this in favor of #95, #96, #97 and #98.

**Comment by stoeffel** [comment]
> Closing this in favor of #95, #96, #97 and #98.

:+1: to all of that will take sometime though.

**Comment by tomekwi** [comment]
Yeah, definitely. That’s why I wrote it down :)
